[package]
name = "Gui_src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "*"#:Shll界面>
anyhow = "*"#:Result兼容处理>
ftlog = "*"#log(C)>
